### ISSUE TITLE
UnicodeDecodeError When using plugin in docker container

### ISSUE THREAD

**Issue by ThorJonsson** [jannessm/tensorboard-plugin-geometry#1]
Hi, 

Thanks for this package, it seems like a very useful tool for monitoring experiments with point clouds. Unfortunately I'm having issues using it. Whenever I load the geometries tab in tensorboard the code fails due to

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 75867: ordinal not in range(128) 

I'm using Docker with Ubuntu 18. I'm unsure how to navigate around this issue. 

Full traceback:

```
root@7b0ded44debb:/home/ubuntu/tensorboard-plugin-geometry# tensorboard --logdir tensorboard_plugin_geometry --bind_all 
                                                    TensorFlow installation not found - running with reduced feature set.                                                                                                       TensorBoard 2.4.0 at http://7b0ded44debb:6006/ (Press CTRL+C to quit)                                                                                                       W0115 03:36:16.701991 140453975090944 security_validator.py:51] In 3.0, this warning will become an error:                                                                  X-Content-Type-Options is required to be "nosniff"                                                                                                                          /usr/local/lib/python3.6/dist-packages/werkzeug/filesystem.py:60: BrokenFilesystemWarning: Detected a misconfigured UNIX 
                                                   filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii'                                                                                                                                                             BrokenFilesystemWarning,                                                                                                                                                  E0115 03:36:16.899390 140453975090944 _internal.py:113] Error on request:                                                                                                   Traceback (most recent call last):                                                                                                                                            
File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 323, in run_wsgi                                                                                      execute(self.server.app)                                                                                                                                                  
File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 312, in execute                                                                                       application_iter = app(environ, start_response)                                                                                                                           
File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 526, in __call__                                                                       return self._app(environ, start_response)                                                                                                                                 
File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 567, in wrapper                                                                        return wsgi_app(environ, start_response)                                                                                                                                  
File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/security_validator.py", line 82, in __call__                                                                 return self._application(environ, start_response_proxy)                                                                                                                   File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/path_prefix.py", line 71, in __call__                                                                        return self._application(environ, start_response)                                                                                                                         `
File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/experiment_id.py", line 76, in __call__                                                                      return self._application(environ, start_response)                                                                                                                         
File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/empty_path_redirect.py", line 47, in __call__                                                                return self._application(environ, start_response)                                                                                                                         
File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 590, in wrapper                                                                        return wsgi_app(environ, start_response)                                                                                                                                  
File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 554, in _route_request                                                                 environ, start_response                                                                                                                                                   
File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_request.py", line 238, in application                                                                     resp = f(*args[:-2] + (request,))                                                                                                                                         
File "/home/ubuntu/tensorboard-plugin-geometry/tensorboard_plugin_geometry/plugin.py", line 65, in _serve_js                                                                  contents = infile.read()                                                                                                                                                  
File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode                                                                                                              return codecs.ascii_decode(input, self.errors)[0]                                                                                                                       UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 75867: ordinal not in range(128) 

```

**Comment by jannessm** [comment]
Hi,

Thank you for using my plugin. I will have a look at this problem as fast as possible.

Since you are dealing with point clouds, you could also try the mesh component of tensor board itself. Or are you using any additional future of my plugin?

Regards,
Jannes

**Comment by jannessm** [comment]
I have ensured now that the files are read as 'utf-8'. So please try version 0.4.1, if the error still persists and give me some feedback.

**Comment by ThorJonsson** [comment]
Thank you so much for your swift response this works! Btw I'd recommend you put a link to the github repo in the description of your pip package, makes it easier to find ;) Thanks for your awesome work, I really like the simplicity of this api.

**Comment by jannessm** [comment]
Awesome! Thank you for your positive response! If you find any other bug, let me know :)
